baseURL: "https://testengineeringnotes.com/"
title: Test Engineering Notes
theme: PaperMod
env: production

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    contentDir: "content/en"
    languageCode: "en-us"
    weight: 1
    menus:
      main:
        - identifier: about
          name: About
          url: /en/about/
          weight: 10
        - identifier: talks
          name: Talks
          url: /en/talks/
          weight: 20
        - identifier: tags
          name: Tags
          url: /en/tags/
          weight: 30
        - identifier: archives
          name: Archives
          url: /en/archives/
          weight: 40
        - identifier: search
          name: Search
          url: /en/search/
          weight: 50
  ua:
    languageName: "Українська"
    contentDir: "content/ua"
    languageCode: "uk-ua"
    weight: 2
    menus:
      main:
        - identifier: about
          name: Про мене
          url: /ua/about/
          weight: 15
        - identifier: talks
          name: Доповіді
          url: /ua/talks/
          weight: 25
        - identifier: tags
          name: Теги
          url: /ua/tags/
          weight: 35
        - identifier: archives
          name: Архів
          url: /ua/archives/
          weight: 45
        - identifier: search
          name: Пошук
          url: /ua/search/
          weight: 55

googleAnalytics: G-EV1R3RYC5R
params:
  cover:
    linkFullImages: false
  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"
  comments: true
  defaultTheme: auto
  homeInfoParams:
    Title: "Test Engineering Notes"
    Content: "By Oleksandr Romanov"
  socialIcons:
    - name: github
      url: "https://github.com/alexromanov"
    - name: twitter
      url: "https://twitter.com/al8xr"
    - name: linkedin
      url: "https://www.linkedin.com/in/oleksandr-romanov/"
    - name: telegram
      url: "https://t.me/testengineering"

  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowToc: true
  ShowCodeCopyButtons: true
  outputs:
    home:
      - HTML
      - RSS
      - JSON
